spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
#    initialization-mode: always
#    data: classpath:import.sql
  jpa:
    hibernate:
      ddl-auto: create-drop

    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logbook:
  filter.enabled: true
  format.style: http
  write:
    max-body-size: 1000

final:
  project:
    testProperty: siemanko

